server.modules = ("mod_access", "mod_accesslog")
server.document-root = "/var/www/homer"
server.port = 8080
server.username = "www-data"
server.groupname = "www-data"
mimetype.assign = (
  ".html" => "text/html",
  ".css" => "text/css",
  ".js" => "application/javascript",
  ".json" => "application/json",
  ".png" => "image/png",
  ".svg" => "image/svg+xml",
  ".ico" => "image/x-icon",
  ".yml" => "text/yaml",
  ".woff2" => "font/woff2",
  ".woff" => "font/woff"
)
index-file.names = ("index.html")

